title: This is the best research in the whole world!

# Where things are
source: .
destination: ./_site
plugins_dir: _plugins # takes an array of strings and loads plugins in that order
layouts_dir: _layouts
data_dir: _data
includes_dir: _includes
collections:
  abstract:
    output: true
    permalink: /:path/

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Outputting
permalink: date
paginate_path: /page:num
timezone: null

# Collections
collections:
  abstract:
    output: true